---
- name: Check if oVirt metrics config.yml file exist
  ansible.builtin.stat:
    path: "{{ ovirt_metrics_config_yml_file }}"
  register: stat_result
  run_once: true
  delegate_to: localhost

- name: Include oVirt metrics config.yml file
  ansible.builtin.include_vars:
    file: '{{ ovirt_metrics_config_yml_file }}'
  when: stat_result.stat.exists
  run_once: true
  delegate_to: localhost

- name: Include oVirt metrics config.yml.d vars directory
  ansible.builtin.include_vars:
    dir: '{{ ovirt_metrics_config_yml_dir }}'
    ignore_files: ['README.md']
  run_once: true
  delegate_to: localhost
