---
- name: Install collectd package
  ansible.builtin.yum:
    name: '{{ collectd_package_name }}'
    state: present
  when: manage_packages|default(true)
  notify: Restart collectd

- name: Install collectd plugins on engine
  ansible.builtin.yum:
    name: '{{ collectd_engine_plugin_packages }}'
    state: present
  when:
    - manage_packages|default(true)
    - ovirt_metrics_host_deploy is undefined
    - inventory_hostname in groups.engine
  notify: Restart collectd

- name: Install collectd plugins on hosts
  ansible.builtin.yum:
    name: '{{ collectd_host_plugin_packages }}'
    state: present
  when:
    - manage_packages|default(true)
    - ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
  notify: Restart collectd

- name: Install collectd write_syslog plugin
  ansible.builtin.yum:
    name: '{{ collectd_write_syslog_package }}'
    state: present
  when:
    - manage_packages|default(true)
    - logging_collector == "rsyslog"
  notify: Restart collectd

- name: Check if 90-default-plugins-* files if exist
  ansible.builtin.find:
    paths: /etc/collectd.d/
    patterns: 90-default-plugins-*
  register: files_to_delete

- name: Ansible remove 90-default-plugins-* files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
