---
# collectd package name.
collectd_package_name: collectd

# a list of additional packages to install (presumably ones that
# provide collectd plugins).
collectd_engine_plugin_packages:
  - collectd-disk
  - collectd-write_http
  - collectd-postgresql

# a list of additional packages to install (presumably ones that
# provide collectd plugins).
collectd_host_plugin_packages:
  - collectd-disk
  - collectd-write_http
  - collectd-virt

# When logging collector is Rsyslog, the write_syslog plugin is used to
# send the metrics to Rsyslog.
collectd_write_syslog_package:
  - collectd-write_syslog
