- name: Configure fluentd system configurations
  ansible.builtin.template:
    src: ovirt-fluentd-system-configurations.conf
    dest: '{{ fluentd_config_parts_dir }}/05-ovirt-fluentd-system-configurations.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: Restart fluentd
