---
- name: Enable collectd
  ansible.builtin.service:
    name: '{{ collectd_service_name }}'
    enabled: true
  when: manage_services|default(true)

- name: Set collectd_tcp_network_connect
  ansible.posix.seboolean:
    name: collectd_tcp_network_connect
    state: true
    persistent: true
  when: 'ansible_selinux.mode in ["enforcing", "permissive"]'

- name: Place global-configuration
  ansible.builtin.template:
    src: global_configuration.conf.j2
    dest: /etc/collectd.d/05-global-configuration.conf
    mode: "0644"
  notify: Restart collectd

- name: Check if libvirt.conf file exist
  ansible.builtin.stat:
    path: /etc/collectd.d/libvirt.conf
  register: libvirt_conf_exists

- name: Overwrite libvirt.conf content
  ansible.builtin.copy:
    content: '# included in 20-builtins-conf-for-ovirt.conf'
    dest: /etc/collectd.d/libvirt.conf
    mode: "0644"
  when: libvirt_conf_exists.stat.exists
  notify: Restart collectd
