---
- name: Enable collectd
  service:
    name: '{{ collectd_service_name }}'
    enabled: yes
  when: manage_services|default(true)

- name: Set collectd_tcp_network_connect
  seboolean:
    name: collectd_tcp_network_connect
    state: yes
    persistent: yes
  when: 'ansible_selinux.mode in ["enforcing", "permissive"]'

- name: Place global-configuration
  template:
    src: global_configuration.conf.j2
    dest: /etc/collectd.d/05-global-configuration.conf
    mode: 0644
  notify: restart collectd

- name: Check if libvirt.conf file exist
  stat:
    path: /etc/collectd.d/libvirt.conf
  register: libvirt_conf_exists

- name: Overwrite libvirt.conf content
  copy:
    content: '# included in 20-builtins-conf-for-ovirt.conf'
    dest: /etc/collectd.d/libvirt.conf
    mode: 0644
  when: libvirt_conf_exists.stat.exists
  notify: restart collectd
