---
- name: Remove write_http config
  ansible.builtin.file:
    state: absent
    path: /etc/collectd.d/30-write_http.conf
  when: logging_collector|d('fluentd') == 'rsyslog'
  notify: Restart collectd

- name: Remove write_syslog config
  ansible.builtin.file:
    state: absent
    path: /etc/collectd.d/30-write_syslog.conf
  when: logging_collector|d('fluentd') == 'fluentd'
  notify: Restart collectd

- name: Place write_http config
  ansible.builtin.template:
    src: write-http.conf.j2
    dest: /etc/collectd.d/30-write_http.conf
    mode: "0644"
  when: logging_collector|d('fluentd') == 'fluentd'
  notify: Restart collectd

- name: Set ovirt_vds_vds_id fact
  ansible.builtin.set_fact:
    ovirt_vds_vds_id: '00000000-0000-0000-0000-000000000000'
  when: not ovirt_vds_vds_id is defined


- name: Place write_syslog config
  ansible.builtin.template:
    src: write-rsyslog.conf.j2
    dest: /etc/collectd.d/30-write_syslog.conf
    mode: "0644"
  when: logging_collector|d('fluentd') == 'rsyslog'
  notify: Restart collectd
