---
- name: Configure oVirt engine processing on undefined host deploy
  when: ovirt_metrics_host_deploy is undefined and inventory_hostname in groups.engine
  block:
    - name: Configure oVirt engine processing
      ansible.builtin.template:
        src: ovirt-engine-processing.conf
        dest: '{{ fluentd_config_parts_dir }}/20-ovirt-engine-processing.conf'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: Restart fluentd
