---
- name: Configure http input
  ansible.builtin.template:
    src: http-input.conf
    dest: '{{ fluentd_config_parts_dir }}/10-http-input.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: Restart fluentd
