- name: Configure oVirt processing
  ansible.builtin.template:
    src: ovirt-post-processing-common.conf
    dest: '{{ fluentd_config_parts_dir }}/25-ovirt-post-processing-common.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: Restart fluentd
