---
- block:
    - name: Place read_statsd-config
      template:
        src: read-statsd.conf.j2
        dest: /etc/collectd.d/10-read-statsd.conf
      notify: restart collectd

    - name: Allow collectd to listen on statsd port
      ansible.builtin.command: semanage port -m -t collectd_port_t -p udp "{{ collectd_read_statsd_port }}"
      when: 'ansible_selinux.mode in ["enforcing", "permissive"]'
      notify: restart collectd
  when: ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
