---
- name: Start up read statsd configuration
  when: ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
  block:
    - name: Place read_statsd-config
      ansible.builtin.template:
        src: read-statsd.conf.j2
        mode: "0644"
        dest: /etc/collectd.d/10-read-statsd.conf
      notify: Restart collectd

    - name: Allow collectd to listen on statsd port
      ansible.builtin.command: semanage port -m -t collectd_port_t -p udp "{{ collectd_read_statsd_port }}"
      changed_when: false
      when: 'ansible_selinux.mode in ["enforcing", "permissive"]'
      notify: Restart collectd
