---
- name: Install fluentd package
  ansible.builtin.yum:
    name: '{{ fluentd_package_name }}'
    state: present
  when: manage_packages|default(true)
  notify: Restart fluentd

- name: Install fluentd engine plugins
  ansible.builtin.yum:
    name: '{{ fluentd_engine_plugin_packages }}'
    state: present
  when:
    - manage_packages|default(true)
    - ovirt_metrics_host_deploy is undefined
    - inventory_hostname in groups.engine
  notify: Restart fluentd

- name: Install fluentd host plugins
  ansible.builtin.yum:
    name: '{{ fluentd_host_plugin_packages }}'
    state: present
  when:
    - manage_packages|default(true)
    - ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
  notify: Restart fluentd
