---
- name: Configure oVirt engine logs processing
  when: ovirt_metrics_host_deploy is undefined and inventory_hostname in groups.engine
  block:
    - name: Ensure fluentd pos_files directory exists
      ansible.builtin.file:
        path: '{{ fluentd_pos_files_dir }}'
        state: directory
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_pos_files_dir_mode }}'

    - name: Create ovirt-engine.log.pos
      ansible.builtin.copy:
        content: ""
        dest: '{{ fluentd_ovirt_engine_log_pos_file }}'
        force: false
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_pos_files_mode }}'
      notify: Restart fluentd

    - name: Configure oVirt engine logs processing
      ansible.builtin.template:
        src: ovirt-engine-processing.conf
        dest: '{{ fluentd_config_parts_dir }}/20-ovirt-engine-logs-processing.conf'
        owner: '{{ fluentd_owner }}'
        group: '{{ fluentd_group }}'
        mode: '{{ fluentd_config_mode }}'
      notify: Restart fluentd
