---
- name: Get ovirt_engine_fqdn
  delegate_to: localhost
  ansible.builtin.shell: ". {{ engine_prolog_path }}; echo $ENGINE_FQDN"
  run_once: true
  register: ovirt_engine_fqdn_result
  changed_when: false

- name: Save ovirt_engine_fqdn as fact
  ansible.builtin.set_fact:
    ovirt_engine_fqdn: "{{ ovirt_engine_fqdn_result.stdout }}"
  run_once: true

- name: Get ovirt_engine_db_name
  delegate_to: localhost
  ansible.builtin.shell: ". {{ engine_prolog_path }}; echo $ENGINE_DB_DATABASE"
  register: ovirt_engine_db_name_result
  changed_when: false

- name: Save ovirt_engine_db_name as fact
  ansible.builtin.set_fact:
    ovirt_engine_db_name: "{{ ovirt_engine_db_name_result.stdout }}"

- name: Get ovirt_engine_db_user
  delegate_to: localhost
  ansible.builtin.shell: ". {{ engine_prolog_path }}; echo $ENGINE_DB_USER"
  register: ovirt_engine_db_user_result
  changed_when: false

- name: Save ovirt_engine_db_user as fact
  ansible.builtin.set_fact:
    ovirt_engine_db_user: "{{ ovirt_engine_db_user_result.stdout }}"

- name: Get ovirt_engine_history_db_name
  delegate_to: localhost
  ansible.builtin.shell: ". {{ engine_prolog_path }}; echo $DWH_DB_DATABASE"
  register: ovirt_engine_history_db_name_result
  changed_when: false

- name: Save ovirt_engine_db_name as fact
  ansible.builtin.set_fact:
    ovirt_engine_history_db_name: "{{ ovirt_engine_history_db_name_result.stdout }}"

- name: Get ovirt_engine_history_db_user
  delegate_to: localhost
  ansible.builtin.shell: ". {{ engine_prolog_path }}; echo $DWH_DB_USER"
  register: ovirt_engine_history_db_user_result
  changed_when: false

- name: Save ovirt_engine_history_db_user as fact
  ansible.builtin.set_fact:
    ovirt_engine_history_db_user: "{{ ovirt_engine_history_db_user_result.stdout }}"
