---
- name: Execute config actions for ovirt host
  when: ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
  block:
    - name: Place builtins-conf-for-ovirt-config
      ansible.builtin.template:
        src: builtins-conf-for-ovirt.conf.j2
        dest: /etc/collectd.d/20-builtins-conf-for-ovirt.conf
        mode: "0644"
      notify: Restart collectd
