---
- name: Set failed validation
  ansible.builtin.set_fact:
    failed_validation: true

- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Stop collectd service
  ansible.builtin.service:
    name: collectd
    state: stopped
    enabled: false
  failed_when: false
