---
#  notify: Set failed validation

- name: If output plugin is elasticsearch, validate host address is set
  ansible.builtin.debug:
    msg: "elasticsearch_host is not configured. This host will not be configured to send metrics"
  when:
    - elasticsearch_host is undefined or elasticsearch_host == None
    - fluentd_elasticsearch_host is undefined or fluentd_elasticsearch_host == None
    - logging_output_type == "elasticsearch"
  changed_when: true
  notify: Set failed validation

# Task required for backwards compatibility task
- name: Update fluentd_elasticsearch_host
  ansible.builtin.set_fact:
    fluentd_elasticsearch_host: ""
  when: (fluentd_elasticsearch_host is undefined) or (fluentd_elasticsearch_host == "elasticsearch-server.example.com")

- name: Update fluentd_elasticsearch_host if elasticsearch_host is defined
  ansible.builtin.set_fact:
    fluentd_elasticsearch_host: "{{ elasticsearch_host }}"
  when: elasticsearch_host is defined

- name: Set elasticsearch_host if undefined and fluentd_elasticsearch_host is defined
  ansible.builtin.set_fact:
    elasticsearch_host: "{{ fluentd_elasticsearch_host }}"
  when:
    - elasticsearch_host is undefined

- name: Set logging_output_type if undefined and fluentd_elasticsearch_host is defined
  ansible.builtin.set_fact:
    logging_output_type: "{{ fluentd_output_plugin }}"
  when: logging_output_type is undefined

- name: Check collectors base packages availability
  when: logging_collector is undefined or logging_collector == 'rsyslog'
  block:
    - name: Install Rsyslog packages
      ansible.builtin.dnf:
        name: '{{ rsyslog_base_packages }}'
        state: present
      register: rsyslog_install_result
      failed_when: false

    - name: Warn if Rsyslog packages installation failed
      ansible.builtin.debug:
        msg: "Warning: Rsyslog packages installation failed."
      when: rsyslog_install_result.failed

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Check Rsyslog packages are available
      ansible.builtin.set_fact:
        rsyslog_base_packages_available: false
      with_items:
        - "{{ rsyslog_base_packages }}"
      when: item not in ansible_facts.packages

    - name: Set logging_collector as rsyslog
      ansible.builtin.set_fact:
        logging_collector: "rsyslog"
      when:
        - rsyslog_base_packages_available
        - logging_collector is undefined

- name: Install needed packages for Fluentd
  when: not rsyslog_base_packages_available or logging_collector == 'fluentd'
  block:
    - name: Install Fluentd packages
      ansible.builtin.dnf:
        name: '{{ fluentd_base_packages }}'
        state: present
      register: fluentd_install_result
      failed_when: false

    - name: Fail if Fluentd packages installation failed
      ansible.builtin.fail:
        msg: "Fluentd packages installation failed. Please check the logs."
      when: fluentd_install_result.failed

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Check Fluentd packages are available
      ansible.builtin.set_fact:
        fluentd_base_packages_available: false
      with_items:
        - "{{ fluentd_base_packages }}"
      when: item not in ansible_facts.packages

    - name: Set logging_collector as fluentd
      ansible.builtin.set_fact:
        logging_collector: "fluentd"
      when:
        - fluentd_base_packages_available
        - logging_collector is undefined

- name: Validate logging_collector is defined
  ansible.builtin.debug:
    msg: "Logs collector base packages are not available. Metrics role will not be able to continue"
  when: logging_collector is undefined
  changed_when: true
  notify: Set failed validation

- name: Validate Rsyslog logging_collector base packages are available
  ansible.builtin.debug:
    msg: "Rsyslog collector is missing required base packages. Metrics role will not be able to continue"
  when:
    - not rsyslog_base_packages_available
    - logging_collector|d('') == 'rsyslog'
  changed_when: true
  notify: Set failed validation

- name: Validate Fluentd logging_collector base packages are available
  ansible.builtin.debug:
    msg: "Fluentd collector is missing required base packages. Metrics role will not be able to continue"
  when:
    - not fluentd_base_packages_available
    - logging_collector|d('') == 'fluentd'
  changed_when: true
  notify: Set failed validation

- name: Initialize logging collector for correct validations
  when: logging_collector is defined
  block:
    # Rsyslog validations
    - name: Update user configuration required
      ansible.builtin.debug:
        msg: "Please update the 'fluentd_elasticsearch_host' to 'elasticsearch_host' in your configuration file. Please see latest documentation"
      when:
        - logging_collector == "rsyslog"
        - fluentd_elasticsearch_host != None

    - name: If logging collector is rsyslog, validate that the output is elasticsearch
      ansible.builtin.debug:
        msg: "The defined output target is not supported in Rsyslog, please check documentation and update you configuration."
      when:
        - logging_collector == "rsyslog"
        - (logging_output_type == "fluentd") or (logging_output_type == "file")
      changed_when: true
      notify: Set failed validation

    # Fluentd validations
    - name: If output plugin is fluentd, validate host address is set
      ansible.builtin.debug:
        msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
      when:
        - logging_collector == "fluentd"
        - fluentd_fluentd_host is undefined
        - logging_output_type == "fluentd"
      changed_when: true
      notify: Set failed validation
