---
- name: Add metrics store host to inventory
  hosts: engine:hosts

  tasks:
    - name: Cleanup services
      ansible.builtin.include_role:
        name: "oVirt.metrics/roles/ovirt_manage_services"
      vars:
        service_state: stopped
        service_enabled: false
        cleanup_services: true

    - name: Print safe to delete message
      ansible.builtin.debug:
        msg: "It is now safe to delete the oVirt metrics store VMs."
