---
- name: Add metrics store host to inventory
  hosts: engine:hosts

  tasks:
    - name: Cleanup services
      include_role:
        name: "oVirt.metrics/roles/ovirt_manage_services"
      vars:
        service_state: stopped
        service_enabled: no
        cleanup_services: true

    - debug:
        msg: "It is now safe to delete the oVirt metrics store VMs."
      run_once: true
