name: Ansible Lint
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
            pip-command: pip3
          - name: centos-stream-10
            shortcut: cs10
            container-name: el10stream
            pip-command: pip3

    name: ${{ matrix.name }}

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:

    - name: Mark repository as safe
      run: git config --global --add safe.directory "$(pwd)"

    - name: Checkout sources
      uses: ovirt/checkout-action@main

    - name: Install pip deps
      run: ${{ matrix.pip-command }} install ansible-lint==6.22.2

    - name: Install ansible.posix
      run: ansible-galaxy collection install -c ansible.posix

    - name: Running ansible-lint on roles
    # 701 - no 'galaxy_info' found
      run: ansible-lint roles/* -x 701
