name: Ansible Lint
on:
  pull_request:
    branches: [master]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: el8stream
            pip-command: pip3.9
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
            pip-command: pip3

    name: ${{ matrix.name }}

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
    - name: Checkout sources
      uses: ovirt/checkout-action@main

    - name: Install pip deps
      run: ${{ matrix.pip-command }} install "rich<11.0.0" "ansible-lint>=6.0.0,<7.0.0"

    - name: Install ansible.posix
      run: ansible-galaxy collection install -c ansible.posix

    - name: Running ansible-lint on roles
    # 701 - no 'galaxy_info' found
      run: ansible-lint roles/* -x 701
