name: Ansible Lint
on:
  pull_request:
    branches: [master]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: el8stream
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream

    name: ${{ matrix.name }}

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install pip deps
      run: |
          pip3 install --upgrade pip
          pip3 install "rich<11.0.0" "ansible-lint<5.0.0"

    - name: Running ansible-lint on roles
    # 701 - no 'galaxy_info' found
      run: ansible-lint roles/* -x 701
